name:  dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # or specify a specific version like '3.13.0'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Verify formatting
        run: flutter format --set-exit-if-changed .
      
      - name: Analyze project source
        run: flutter analyze
      
      - name: Run tests
        run: flutter test
      
      # Optional: Build the app (uncomment if needed)
      # - name: Build APK
      #   run: flutter build apk --release
      #
      # - name: Build IPA
      #   run: flutter build ios --release --no-codesign
